apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: democicd
spec:
  replicas: 1
  
  template:
    metadata:
      labels:
        app: democicd
    spec:
      containers:
      - name: my-app
        image: agawande/my-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: democicd
spec:
  type: LoadBalancer
  ports:
  -protocol:TCP
  -port: 80
  -targetPort: 8080
  selector:
    app: democicd
